version: "3"
services:
        app:
                build:
                        context: .
                ports:
                        - "5000:5000"
                volumes:
                        - ./:/usr/src/app

                command: >
                        sh -c "yarn start"
